### ISSUE TITLE
tempo and rhythm enhancements

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#221]
[cc @mprockup]

The current functionality for tempo and rhythm is pretty basic; we should do something about that.

#210 improves the basic onset strength implementation.  From that, we can add a few interesting pieces, such as tempo-invariant rhythm descriptors via the Mellin scale transform (see [here](http://www.csd.uoc.gr/~hannover/MMILab-Andre_files/HolzapfelIEEEScale.pdf)), and some of the multi-band accent descriptors from @mprockup.

This will be a not-small job, and probably require many PRs.

For now, we should make a list of functions to be added.  Please revise and expand as needed in comments below.

- [x] #231 mellin scale transform
- [x] #226 multi-band onset aggregation.  This can probably be done by passing band markers into `onset_strength`.
- ~~DCT+median filtering?~~
- ~~local onset strength (onset.onset_strength + util.frame, plus some convenient defaults to make it line up with spectral features)~~
- [x] #247 local onset autocorrelation (short-time tempogram)
- [x] #251 fix onset alignment to match input spectrogram

**Comment by dpwe** [comment]
May I take a stab at demystifying the Mellin transform?

The idea is to represent the autocorrelation on a log-lag time scale
(it has to be the autocorrelation, because we need a fixed zero-time
reference).  As with log-frequency, this mapping transforms a
*scaling* of the linear axis (i.e., a tempo change) to a *shift* in
the log-scale axis.  The Mellin transform then takes the Fourier
transform of this representation, whose magnitude, of course, is
invariant to shifts (excluding edge effects).

A log-lag axis poses problems for small time intervals, just as a
log-frequency axis poses problems for low frequencies.

A complete invariance to tempo invariance raises the risk of
inadvertently matching things that have very large differences in
tempo, which is probably not the perceptual equivalence we're hoping
for.  But I guess choosing the actual range of log-lag values that are
sampled (i.e., determining the impact of the edge effects) can control
this.

  DAn.

**Comment by dpwe** [comment]
By which I meant to say: I think log-lag autocorrelation is a
generally useful and intuitive representation, much like log-frequency
spectrum.

  DAn.

**Comment by bmcfee** [comment]
multi-band onsets are now in place after merging #229.

**Comment by bmcfee** [comment]
Is there a canonical parameterization for the (discrete) scale transform?

I have an implementation that basically works -- as in, produces comparable figures to those in [the paper linked above](http://www.csd.uoc.gr/~hannover/MMILab-Andre_files/HolzapfelIEEEScale.pdf) -- but there appear to be a few different ways to specify the parameters.  Specifically, we need to set:

* minimum lag
* maximum lag 
* bin width (delta-c in the paper, set to `pi / log(1 + lag_max / lag_min)`
* # scale components

minimum lag is obviously necessary from the definition (eq. 4 in the paper), but it seems to me that we only need at most 2 of the remaining 3.  So which are the most natural to use?  (Or am I mistaken?)

**Comment by dpwe** [comment]
I think the natural thing is to set min_lag, bin-to-bin ratio, and number
of bins. Harder to be off-by-one and end up missing all the integer steps.

Bin-to-bin ratio can be parametrized as bins per octave, for extra
friendliness to those who think that way (and compatibility with cq filter
bank syntax, maybe?)

  DAn.

**Comment by bmcfee** [comment]
> and compatibility with cq filter
> bank syntax, maybe?

Seems like reason enough for me!

**Comment by bmcfee** [comment]
Note: we'll most likely need to introduce a `feature.rhythm` submodule to separate out dependencies for feature functions that depend on onset strength calculation.

**Comment by bmcfee** [comment]
The lagged difference approximation taken in the direct scale transform has been bugging me since I first read about it.  After digging up the derivation (eq. A3 [here](http://www.sciencedirect.com/science/article/pii/S0888327000912962)), I now see why: it's separating the integral by assuming `f(e^t)` is constant for `t = [ln(kT), ln((k+1)T)]`.  This works out fine for `T=1` (minimum lag of one sample), but it seems pretty bad for larger values that we might want to support.

Would it not be a better (but still crude) approximation to use the average value of `f` over the k'th interval?  It's not much work to replace the direct sub-sampling by a windowed aggregation/sync call, and then the rest of the code proceeds as before.  (I have a prototype working in a notebook, and it seems okay so far.)

**Comment by bmcfee** [comment]
After a bit of experimentation, I think we should skip the Williams & Zaluba algorithm, and instead use DeSena's fast Mellin transform algorithm.  There are a few reasons for this:

* FMT is asymptotically faster, since it's FFT-based rather than explicitly constructing an O(n^2) basis
* The parameters are simpler to grasp: interpolation mode and over-sampling factor, rather than C_max/bin-spacing/etc
* The implementation itself is a bit simpler, and lends itself more naturally to a matching inverse transform
* The implementation trivially supports generalization from the scale transform to other (real-parameterized) Mellin transforms.  I don't have a use-case in mind for this, but it's a nice bonus.

**Comment by bmcfee** [comment]
merging #231 resolves this issue.
